name: LocalXpose Tunnel

on:
  push:
    branches:
      - main

jobs:
  tunnel:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to LocalXpose
        run: .\loclx.exe account login --token 6kvFHtPDBIrUvDeNCZx52B8QFyiFj3L1VdDOdpKZ

      - name: Start Tunnel
        run: .\loclx.exe tunnel tcp --to localhost:3389
